/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLGraderecorder_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   graderecorder/v1
// Description:
//   Grade Recorder API

#import "GTLGraderecorderConstants.m"

#import "GTLGraderecorderAssignment.m"
#import "GTLGraderecorderAssignmentCollection.m"
#import "GTLGraderecorderGradeEntry.m"
#import "GTLGraderecorderGradeEntryCollection.m"
#import "GTLGraderecorderStudent.m"
#import "GTLGraderecorderStudentCollection.m"

#import "GTLQueryGraderecorder.m"
#import "GTLServiceGraderecorder.m"
